### ISSUE TITLE
Feedback for “CommandOptions”

### ISSUE THREAD

**Issue by exitss** [underctrl-io/commandkit#42]
**guildOnly listed here**

![68470976f620ae4d9898](https://github.com/underctrl-io/commandkit/assets/67079527/bb36d3cc-ddb9-445f-9ce4-a4896e8d4d20)
**but not here**

![409811ce315742e70769](https://github.com/underctrl-io/commandkit/assets/67079527/5ba8f1c1-554b-43c3-b574-2d33332d0305)

**Comment by m1-dev** [comment]
We'll remove it from the documentation. Thank you for pointing this out.
