### ISSUE TITLE
Search bar not working on docs website

### ISSUE THREAD

**Issue by Firgrep** [underctrl-io/commandkit#6]
Really smooth transition between pages on your docs website - very cool! But I notice the search bar isn't working. Just opens a gray box when you click it.

**Comment by notunderctrl** [comment]
Interesting. I can't seem to get the same issue. Here's what I get:
![image](https://github.com/underctrl-io/commandkit/assets/119873044/6499489c-7c94-45bb-b1da-86cd2c760616)

Can you check your network tab for any failed requests? This is what it looks like for me:
![image](https://github.com/underctrl-io/commandkit/assets/119873044/5aa2a42d-beed-4592-ba36-a9959ab2eaff)

**Comment by Firgrep** [comment]
So when I open the site in a new window (incognito just to be sure), and I click the search bar, it opens up as expected with the little white box inside the gray one. 
![Screenshot 2023-09-09 14 18 52](https://github.com/underctrl-io/commandkit/assets/118931755/1203b4e7-1f99-4200-a6a2-6a6e16477bb5)

But as soon as I click to enter the docs and try the search bar again, a non-interactive gray box opens. 
![Screenshot 2023-09-09 14 21 01](https://github.com/underctrl-io/commandkit/assets/118931755/70ec7405-f234-46c8-b657-bb839a1c20e9)

I suspect this is something to do with the ViewTransitions. I think I heard somewhere that it may turn off javascript and that you have to do something extra in order to re-enable it. E.g. https://youtu.be/lsXqparnx24?si=ayV0NVg5OD6JpBSc&t=135 he says you have to add `transition:persist` to the HTML element and any state attached to it. I'm sure there is more info about this.

**Comment by notunderctrl** [comment]
I can confirm this does happen after a page switch, although I'm not sure why. As far as I can tell,`transition:persist` can only be used with HTML elements. I've opened a [support thread](https://discord.com/channels/830184174198718474/1150044043909267486) in the Astro Discord to see if it's possible to use a layout for all the markdown content. Hopefully this can make it easier to ensure that the JavaScript for the search functionality is executed on every page load.

**Comment by notunderctrl** [comment]
The docs are now using Next.js, marking this issue solved.

**Comment by Firgrep** [comment]
Interesting choice! Looks very cool. I've also been trying out Nextra with a project I'm working on. Best of luck!

**Comment by notunderctrl** [comment]
Nextra is definitely more production ready. I think you'll love it
