### ISSUE TITLE
Import.meta doesn't work on TS

### ISSUE THREAD

**Issue by RainbowCreamPie** [underctrl-io/commandkit#8]
![image](https://github.com/underctrl-io/commandkit/assets/136293817/82463c9b-66ab-4de9-afec-d27a2f140939)
What should I do??

**Comment by notunderctrl** [comment]
`import.meta` only works in ESM. With your current setup, you already have `__dirname` available.

**Comment by not-core-i9** [comment]
real

**Comment by SlmixX** [comment]
> `import.meta` only works in ESM. With your current setup, you already have `__dirname` available.

my man
