### ISSUE TITLE
CommandData typings

### ISSUE THREAD

**Issue by feelthatvib3** [underctrl-io/commandkit#9]
Hello, I've recently bumped into an error while coding a simple command that accepts a string option.

(I removed name & description for the sake of focusing on the main problem here)
```ts
export const data: CommandData = {
    name: "",
    description: "",
    options: [
        {
            name: "",
            description: "",
            type: ApplicationCommandOptionType.String,
            required: true,
        },
    ],
};
```

Here it gives me an error:
```ts
Type 'ApplicationCommandOptionType.String' is not assignable to type 'ApplicationCommandOptionType.Subcommand | ApplicationCommandOptionType.SubcommandGroup'.
```

Looking at the `CommandData` type here I've noticed that it might be lacking `APIApplicationCommandBasicOption` in `Array<APIApplicationCommandSubcommandOption | APIApplicationCommandSubcommandGroupOption>`.
```ts
type CommandData = {
    name: string;
    description: string;
    type?: CommandType;
    name_localizations?: Partial<Record<LocaleString, string | null>>;
    description_localizations?: Partial<Record<LocaleString, string | null>>;
    dm_permission?: boolean;
    default_member_permissions?: string;
    nsfw?: boolean;
    options?: Array<APIApplicationCommandSubcommandOption | APIApplicationCommandSubcommandGroupOption>;
};
```

However, looking at the code in `src/types/index.ts`:
```ts
type BaseCommandData = {
    name: string;
    type?: CommandType;
    name_localizations?: Partial<Record<LocaleString, string | null>>;
    dm_permission?: boolean;
    default_member_permissions?: string;
    nsfw?: boolean;
};

type ChatInputCommandData = BaseCommandData & {
    type?: CommandType.ChatInput;
    description: string;
    description_localizations?: Partial<Record<LocaleString, string | null>>;
    options?: Array<APIApplicationCommandOption>;
};

type UserOrMessageCommandData = BaseCommandData & {
    type: CommandType.User | CommandType.Message;
};

export type CommandData = ChatInputCommandData | UserOrMessageCommandData;
```

You are actually using `APIApplicationCommandOption` which kind of covers all the types as the [official discord.js documentation](https://discord-api-types.dev/api/discord-api-types-v10#APIApplicationCommandOption) suggests.

Not exactly sure what causes the issue here, but I thought it would be good to report a problem.

**Comment by notunderctrl** [comment]
Hello.

I can confirm this happens in version 0.1.1
I realized I pushed a fix for this issue but completely forgot to push a package update after doing so.
Version [0.1.2](https://github.com/underctrl-io/commandkit/releases/tag/v0.1.2) fixes this bug.

Thanks for pointing it out 💪

**Comment by notunderctrl** [comment]
Realized the bug I mentioned before closing this was different so apologies for that.
I'll be looking into this issue. Thanks for bringing it up!

**Comment by notunderctrl** [comment]
Version [0.1.2](https://github.com/underctrl-io/commandkit/releases/tag/v0.1.2) fixes this issue. Thanks for pointing it out :)
